CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(500) NOT NULL,
    "ISBN" character varying(20) NOT NULL,
    "PublicationYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE "Members" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    CONSTRAINT "PK_Members" PRIMARY KEY ("Id")
);

CREATE TABLE "Loans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BookId" integer NOT NULL,
    "MemberId" integer NOT NULL,
    "LoanDate" timestamp with time zone NOT NULL,
    "ReturnDate" timestamp with time zone,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Loans_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Loans_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES "Members" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Loans_BookId" ON "Loans" ("BookId");

CREATE INDEX "IX_Loans_MemberId" ON "Loans" ("MemberId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305161141_InitialSchema', '8.0.11');

COMMIT;

