START TRANSACTION;

CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Biography" character varying(2000),
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "BookAuthors" (
    "BookId" integer NOT NULL,
    "AuthorId" integer NOT NULL,
    "OrderIndex" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_BookAuthors" PRIMARY KEY ("BookId", "AuthorId"),
    CONSTRAINT "FK_BookAuthors_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BookAuthors_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id") ON DELETE CASCADE
);

INSERT INTO "Authors" ("Id", "Biography", "FirstName", "LastName")
VALUES (1, NULL, 'Unknown', '');


                INSERT INTO "BookAuthors" ("BookId", "AuthorId", "OrderIndex")
                SELECT "Id", 1, 0
                FROM "Books"
                WHERE NOT EXISTS (
                    SELECT 1 FROM "BookAuthors" 
                    WHERE "BookAuthors"."BookId" = "Books"."Id"
                );
            

CREATE INDEX "IX_BookAuthors_AuthorId" ON "BookAuthors" ("AuthorId");

SELECT setval(
    pg_get_serial_sequence('"Authors"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Authors") + 1,
        nextval(pg_get_serial_sequence('"Authors"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305162118_AddAuthorsAndBookAuthors', '8.0.11');

COMMIT;

